server:
  port: 11001

spring:
  profiles:
    active: dev
  application:
    name: service-vod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///glkt_vod?characterEncoding=utf-8&useSSL=false
    username: root
    password: root123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jdbc:
    template:
      query-timeout: 1000
  mvc:
    path match:
      # 解决swagger不兼容springmvc的问题
      matching-strategy: ant_path_matcher
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# page helper
page helper:
  helper-dialect: mysql
  reasonable: true

tencent:
  cos:
    file:
      region: xxxxxxxxxxxx
      secretId: xxxxxxxxxxxx
      secretKey: xxxxxxxxxxxx
      bucketName: xxxxxxxxxxxx


