server:
  port: 11001

spring:
  profiles:
    active: dev
  application:
    name: service-vod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///glkt_vod?characterEncoding=utf-8&useSSL=false
    username: root
    password: root123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    path match:
      # 解决swagger不兼容springmvc的问题
      matching-strategy: ant_path_matcher
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl